const CAFE_INFO = {
  name: "کافه اِسپرسو",
  name_en: "Espresso Café",
  slogan: "هر فنجان، یک تجربه",
  logo: "images/espresso_cafe_logo.svg",
  phone: ["021-88001234", "021-88001235"],
  mobile: "0912-345-6789",
  address: "تبریز",
  address_short: "تبریز",
  instagram: "@espresso_cafe",
  telegram: "@espresso_cafe",
  whatsapp: "989123456789",
  email: "info@espressocafe.ir",
  website: "https://espressocafe.ir",
  wifi_name: "Espresso_Guest",
  wifi_password: "Coffee@1402",
  working_hours: {
    weekdays: "۸ صبح تا ۱۱ شب",
    weekends: "۹ صبح تا ۱۲ شب",
    holidays: "۱۰ صبح تا ۱۰ شب",
  },
  social_links: {
    instagram: "https://instagram.com/espresso_cafe",
    telegram: "https://t.me/espresso_cafe",
    whatsapp: "https://wa.me/989123456789",
  },
};

const STORIES = [
  {
    id: 1,
    title: "تخفیف صبحانه",
    image: "images/americano.jpg",
    content_image: "images/americano.jpg",
    color: "#e8a94a",
  },
  {
    id: 2,
    title: "میکس جدید",
    image: "images/blue_lagoon.jpg",
    content_image: "images/blue_lagoon.jpg",
    color: "#4a7c59",
  },
  {
    id: 3,
    title: "محیط کافه",
    image: "images/panini.jpg",
    content_image: "images/panini.jpg",
    color: "#c47b2b",
  },
];

const CATEGORIES = [
  { id: "all", label: "همه", icon: "☕", order: 0 },
  { id: "espresso", label: "اسپرسو", icon: "☕", order: 1 },
  { id: "latte", label: "لاته و کاپوچینو", icon: "🥛", order: 2 },
  { id: "cold", label: "نوشیدنی سرد", icon: "🧊", order: 3 },
  { id: "tea", label: "چای و دمنوش", icon: "🍵", order: 4 },
  { id: "mocktail", label: "موکتیل", icon: "🍹", order: 5 },
  { id: "smoothie", label: "اسموتی", icon: "🥤", order: 6 },
  { id: "cake", label: "کیک و شیرینی", icon: "🎂", order: 7 },
  { id: "snack", label: "ساندویچ و اسنک", icon: "🥪", order: 8 },
];

const PRODUCTS = [
  // ═══════════════════════════════
  //  اسپرسو
  // ═══════════════════════════════
  {
    id: 1,
    name: "اسپرسو",
    name_en: "Espresso",
    category: "espresso",
    price: 35000,
    description: "شات خالص اسپرسو با دانه‌های برزیلی روست‌شده",
    image: "images/espresso.jpg",
    image_placeholder: "#3B1F0A",
    available: true,
    badges: ["popular"],
    options: [
      { label: "سینگل شات", price: 35000 },
      { label: "دابل شات", price: 50000 },
    ],
    calories: 5,
  },
  {
    id: 2,
    name: "امریکانو",
    name_en: "Americano",
    category: "espresso",
    price: 55000,
    description: "اسپرسو با آب داغ، سبک و ملایم",
    image: "images/americano.jpg",
    image_placeholder: "#4A2A10",
    available: true,
    badges: ["popular"],
    options: [
      { label: "کوچک", price: 55000 },
      { label: "بزرگ", price: 70000 },
    ],
    calories: 10,
  },
  {
    id: 3,
    name: "کورتادو",
    name_en: "Cortado",
    category: "espresso",
    price: 65000,
    description: "اسپرسو با کمی شیر داغ — تعادل کامل",
    image: "images/cortado.jpg",
    image_placeholder: "#6B3A1F",
    available: true,
    badges: ["chef_special"],
    calories: 45,
  },
  {
    id: 4,
    name: "ماکیاتو",
    name_en: "Macchiato",
    category: "espresso",
    price: 60000,
    description: "اسپرسو با لایه‌ای از فوم شیر",
    image: "images/macchiato.jpg",
    image_placeholder: "#7A4020",
    available: true,
    badges: [],
    calories: 40,
  },

  // ═══════════════════════════════
  //  لاته و کاپوچینو
  // ═══════════════════════════════
  {
    id: 5,
    name: "کاپوچینو",
    name_en: "Cappuccino",
    category: "latte",
    price: 75000,
    description: "یک‌سوم اسپرسو، یک‌سوم شیر، یک‌سوم فوم — کلاسیک ایتالیایی",
    image: "images/cappuccino.jpg",
    image_placeholder: "#C4956A",
    available: true,
    badges: ["popular"],
    options: [
      { label: "کوچک", price: 75000 },
      { label: "بزرگ", price: 90000 },
    ],
    calories: 120,
  },
  {
    id: 6,
    name: "لاته",
    name_en: "Latte",
    category: "latte",
    price: 80000,
    description: "اسپرسو با شیر بخارپز، لطیف و کرمی",
    image: "images/latte.jpg",
    image_placeholder: "#D4A574",
    available: true,
    badges: ["popular"],
    options: [
      { label: "کوچک ۲۸۰ml", price: 80000 },
      { label: "بزرگ ۴۸۰ml", price: 100000 },
    ],
    calories: 190,
  },
  {
    id: 7,
    name: "لاته وانیل",
    name_en: "Vanilla Latte",
    category: "latte",
    price: 95000,
    description: "لاته با سیروپ وانیل طبیعی — شیرین و خوش‌عطر",
    image: "images/vanilla_latte.jpg",
    image_placeholder: "#E8D5A3",
    available: true,
    badges: ["new"],
    calories: 250,
  },
  {
    id: 8,
    name: "لاته کارامل",
    name_en: "Caramel Latte",
    category: "latte",
    price: 95000,
    description: "لاته با کارامل اصل، شیرین و کرمی",
    image: "images/caramel_latte.jpg",
    image_placeholder: "#C4873A",
    available: true,
    badges: [],
    calories: 280,
  },
  {
    id: 9,
    name: "موکا",
    name_en: "Mocha",
    category: "latte",
    price: 90000,
    description: "اسپرسو با شیر و شکلات تلخ — برای دوستداران کاکائو",
    image: "images/mocha.jpg",
    image_placeholder: "#4A2810",
    available: true,
    badges: ["popular"],
    calories: 300,
  },
  {
    id: 10,
    name: "فلت وایت",
    name_en: "Flat White",
    category: "latte",
    price: 85000,
    description: "دابل شات با میکرو‌فوم — قوی‌تر از لاته",
    image: "images/flat_white.jpg",
    image_placeholder: "#D4B896",
    available: true,
    badges: ["chef_special"],
    calories: 160,
  },
  {
    id: 11,
    name: "لاته دارچین",
    name_en: "Cinnamon Latte",
    category: "latte",
    price: 92000,
    description: "لاته گرم با دارچین سیلانی — عطر پاییز",
    image: "images/cinnamon_latte.jpg",
    image_placeholder: "#B5633A",
    available: true,
    badges: ["new"],
    calories: 230,
  },

  // ═══════════════════════════════
  //  نوشیدنی سرد
  // ═══════════════════════════════
  {
    id: 12,
    name: "آیس لاته",
    name_en: "Iced Latte",
    category: "cold",
    price: 90000,
    description: "لاته سرد با یخ — خنک و سرحال",
    image: "images/iced_latte.jpg",
    image_placeholder: "#C8D8E8",
    available: true,
    badges: ["popular"],
    calories: 170,
  },
  {
    id: 13,
    name: "کلد برو",
    name_en: "Cold Brew",
    category: "cold",
    price: 95000,
    description: "قهوه دم‌کرده ۱۲ ساعت در آب سرد — ملایم و کم‌اسید",
    image: "images/cold_brew.jpg",
    image_placeholder: "#2A1A0A",
    available: true,
    badges: ["chef_special"],
    options: [
      { label: "ساده", price: 95000 },
      { label: "با شیر", price: 110000 },
    ],
    calories: 10,
  },
  {
    id: 14,
    name: "داچ بیبی کلد",
    name_en: "Dalgona Cold",
    category: "cold",
    price: 100000,
    description: "کف دالگونا روی شیر سرد — اینستاگرامی و خوشمزه",
    image: "images/dalgona.jpg",
    image_placeholder: "#D4C090",
    available: true,
    badges: ["new"],
    calories: 320,
  },
  {
    id: 15,
    name: "فراپوچینو شکلات",
    name_en: "Chocolate Frappuccino",
    category: "cold",
    price: 120000,
    description: "قهوه بلند با شکلات و خامه — خنک و شیرین",
    image: "images/frappuccino.jpg",
    image_placeholder: "#5A2E10",
    available: true,
    badges: ["popular"],
    calories: 450,
  },
  {
    id: 16,
    name: "آیس ماچا لاته",
    name_en: "Iced Matcha Latte",
    category: "cold",
    price: 110000,
    description: "پودر ماچا ژاپنی با شیر سرد",
    image: "images/matcha_latte.jpg",
    image_placeholder: "#7A9A4A",
    available: false,
    badges: ["vegan"],
    calories: 180,
  },

  // ═══════════════════════════════
  //  چای و دمنوش
  // ═══════════════════════════════
  {
    id: 17,
    name: "چای ایرانی",
    name_en: "Persian Tea",
    category: "tea",
    price: 35000,
    description: "چای لاهیجان با نبات — اصیل ایرانی",
    image: "images/persian_tea.jpg",
    image_placeholder: "#C4501A",
    available: true,
    badges: [],
    calories: 0,
  },
  {
    id: 18,
    name: "چای ماسالا",
    name_en: "Masala Chai",
    category: "tea",
    price: 60000,
    description: "چای هندی با زنجبیل، هل، دارچین و شیر",
    image: "images/masala_chai.jpg",
    image_placeholder: "#B5703A",
    available: true,
    badges: ["popular"],
    calories: 150,
  },
  {
    id: 19,
    name: "دمنوش لیمو و زنجبیل",
    name_en: "Lemon Ginger Herbal",
    category: "tea",
    price: 55000,
    description: "دمنوش تازه با لیمو ترش و زنجبیل — گرم‌کننده",
    image: "images/lemon_ginger.jpg",
    image_placeholder: "#E8D050",
    available: true,
    badges: ["vegan"],
    calories: 20,
  },
  {
    id: 20,
    name: "دمنوش بابونه و عسل",
    name_en: "Chamomile Honey",
    category: "tea",
    price: 58000,
    description: "بابونه طبیعی با عسل چهل‌گیاه — آرام‌بخش",
    image: "images/chamomile.jpg",
    image_placeholder: "#F0D878",
    available: true,
    badges: ["vegan"],
    calories: 35,
  },
  {
    id: 21,
    name: "دمنوش گل رز و هل",
    name_en: "Rose Cardamom Herbal",
    category: "tea",
    price: 65000,
    description: "ترکیب گل رز ایرانی با هل خوش‌عطر",
    image: "images/rose_tea.jpg",
    image_placeholder: "#F0A0A0",
    available: true,
    badges: ["chef_special"],
    calories: 10,
  },

  // ═══════════════════════════════
  //  موکتیل
  // ═══════════════════════════════
  {
    id: 22,
    name: "موهیتو ویرجین",
    name_en: "Virgin Mojito",
    category: "mocktail",
    price: 95000,
    description: "نعناع تازه، لیمو، شکر و سودا — کلاسیک تابستانی",
    image: "images/mojito.jpg",
    image_placeholder: "#A0D090",
    available: true,
    badges: ["popular", "vegan"],
    calories: 120,
  },
  {
    id: 23,
    name: "بلو لگون",
    name_en: "Blue Lagoon",
    category: "mocktail",
    price: 105000,
    description: "آناناس، نارگیل، لیمو ترش و کوراسائو آبی",
    image: "images/blue_lagoon.jpg",
    image_placeholder: "#4090C8",
    available: true,
    badges: ["new"],
    calories: 180,
  },
  {
    id: 24,
    name: "پاشن فروت موکتیل",
    name_en: "Passion Fruit Mocktail",
    category: "mocktail",
    price: 110000,
    description: "میوه ماراکویای تازه با سودا و نعناع",
    image: "images/passion_fruit.jpg",
    image_placeholder: "#E87820",
    available: true,
    badges: ["chef_special", "vegan"],
    calories: 140,
  },
  {
    id: 25,
    name: "رزماری لمونید",
    name_en: "Rosemary Lemonade",
    category: "mocktail",
    price: 90000,
    description: "لیموناد تازه با رزماری — فریش و اورجینال",
    image: "images/rosemary_lemonade.jpg",
    image_placeholder: "#E8E060",
    available: true,
    badges: ["vegan"],
    calories: 130,
  },

  // ═══════════════════════════════
  //  اسموتی
  // ═══════════════════════════════
  {
    id: 26,
    name: "اسموتی توت‌فرنگی موز",
    name_en: "Strawberry Banana Smoothie",
    category: "smoothie",
    price: 120000,
    description: "توت‌فرنگی تازه، موز، ماست و عسل",
    image: "images/strawberry_smoothie.jpg",
    image_placeholder: "#F07088",
    available: true,
    badges: ["popular"],
    calories: 280,
  },
  {
    id: 27,
    name: "اسموتی سبز",
    name_en: "Green Smoothie",
    category: "smoothie",
    price: 115000,
    description: "اسفناج، آووکادو، موز و شیر نارگیل",
    image: "images/green_smoothie.jpg",
    image_placeholder: "#60A860",
    available: true,
    badges: ["vegan", "chef_special"],
    calories: 240,
  },
  {
    id: 28,
    name: "اسموتی انبه زردآلو",
    name_en: "Mango Apricot Smoothie",
    category: "smoothie",
    price: 125000,
    description: "انبه تازه، زردآلو، هل و شیر — گرمسیری",
    image: "images/mango_smoothie.jpg",
    image_placeholder: "#F0A020",
    available: true,
    badges: ["new", "vegan"],
    calories: 260,
  },

  // ═══════════════════════════════
  //  کیک و شیرینی
  // ═══════════════════════════════
  {
    id: 29,
    name: "چیزکیک نیویورکی",
    name_en: "New York Cheesecake",
    category: "cake",
    price: 95000,
    description: "چیزکیک خامه‌ای با بیسکویت گراهام — خانگی",
    image: "images/cheesecake.jpg",
    image_placeholder: "#F0E0C0",
    available: true,
    badges: ["popular", "chef_special"],
    calories: 420,
    allergens: ["گلوتن", "لبنیات", "تخم‌مرغ"],
  },
  {
    id: 30,
    name: "براونی شکلاتی",
    name_en: "Chocolate Brownie",
    category: "cake",
    price: 75000,
    description: "براونی تر و شکلاتی، گرم سرو می‌شود",
    image: "images/brownie.jpg",
    image_placeholder: "#3A1A08",
    available: true,
    badges: ["popular"],
    options: [
      { label: "ساده", price: 75000 },
      { label: "با بستنی", price: 100000 },
    ],
    calories: 380,
    allergens: ["گلوتن", "لبنیات", "تخم‌مرغ"],
  },
  {
    id: 31,
    name: "کیک لیمو و خشخاش",
    name_en: "Lemon Poppy Cake",
    category: "cake",
    price: 80000,
    description: "کیک ترش با لیمو تازه و دانه خشخاش",
    image: "images/lemon_cake.jpg",
    image_placeholder: "#F0E878",
    available: true,
    badges: ["new"],
    calories: 310,
    allergens: ["گلوتن", "تخم‌مرغ"],
  },
  {
    id: 32,
    name: "تیرامیسو",
    name_en: "Tiramisu",
    category: "cake",
    price: 110000,
    description: "ماسکارپونه ایتالیایی، اسپرسو و پودر کاکائو",
    image: "images/tiramisu.jpg",
    image_placeholder: "#D4A060",
    available: true,
    badges: ["chef_special", "popular"],
    calories: 390,
    allergens: ["گلوتن", "لبنیات", "تخم‌مرغ"],
  },

  // ═══════════════════════════════
  //  ساندویچ و اسنک
  // ═══════════════════════════════
  {
    id: 33,
    name: "ساندویچ کلاب",
    name_en: "Club Sandwich",
    category: "snack",
    price: 145000,
    description: "مرغ گریل، بیکن گوسفند، گوجه، کاهو و سس مخصوص",
    image: "images/club_sandwich.jpg",
    image_placeholder: "#C8A850",
    available: true,
    badges: ["popular"],
    calories: 580,
    allergens: ["گلوتن"],
  },
  {
    id: 34,
    name: "کرواسان کره",
    name_en: "Butter Croissant",
    category: "snack",
    price: 65000,
    description: "کرواسان فرانسوی تازه با کره — گرم",
    image: "images/croissant.jpg",
    image_placeholder: "#D4A840",
    available: true,
    badges: [],
    options: [
      { label: "ساده", price: 65000 },
      { label: "با پنیر", price: 80000 },
      { label: "با ژامبون", price: 90000 },
    ],
    calories: 310,
    allergens: ["گلوتن", "لبنیات"],
  },
  {
    id: 35,
    name: "پانینی قارچ و پنیر",
    name_en: "Mushroom Cheese Panini",
    category: "snack",
    price: 130000,
    description: "پانینی گریل با قارچ، پنیر موزارلا و سس پستو",
    image: "images/panini.jpg",
    image_placeholder: "#8A6830",
    available: true,
    badges: ["new", "chef_special"],
    calories: 490,
    allergens: ["گلوتن", "لبنیات"],
  },
];

function formatPrice(price) {
  return price.toLocaleString("fa-IR") + " تومان";
}

function getProductsByCategory(categoryId) {
  if (categoryId === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === categoryId);
}

function searchProducts(query) {
  const q = query.toLowerCase().trim();
  if (!q) return PRODUCTS;
  return PRODUCTS.filter(
    (p) =>
      p.name.includes(q) ||
      (p.name_en && p.name_en.toLowerCase().includes(q)) ||
      (p.description && p.description.includes(q))
  );
}

const BADGE_LABELS = {
  new: { label: "جدید", color: "#4A7C59", bg: "#EAF3DE" },
  popular: { label: "پرفروش", color: "#854F0B", bg: "#FAEEDA" },
  vegan: { label: "وگان", color: "#3B6D11", bg: "#C0DD97" },
  sugar_free: { label: "بدون شکر", color: "#185FA5", bg: "#B5D4F4" },
  spicy: { label: "تند", color: "#A32D2D", bg: "#F7C1C1" },
  chef_special: { label: "ویژه شف", color: "#533AB7", bg: "#CECBF6" },
};
